import numpy as np


class MicroStepperMotor:
    """
    micro stepper motor model with EM stepping torque, cogging torque, and friction
    """

    def __init__(self, config):
        self.N_r = config.get('N_r', 50)               # Rotor tooth/pole pairs (50 for 1.8 deg stepper)
        self.T_holding = config.get('T_holding', 0.15) # Peak holding torque [N*m]
        self.T_cog = config.get('T_cog', 0.008)        # Cogging torque peak amplitude [N*m]
        self.N_cog = config.get('N_cog', 200)          # Cogging cycles per revolution
        self.B_m = config.get('B_m', 1e-3)             # Viscous damping coefficient [N*m*s/rad]
        self.T_coulomb = config.get('T_coulomb', 0.002) # Coulomb dry friction torque [N*m]

    def compute_motor_torque(self, theta, theta_dot, theta_cmd):
        """
        Computes net torque generated by stepper motor at joint angle theta.
        """
        # 1. Electromagnetic stepping drive torque
        tau_em = -self.T_holding * np.sin(self.N_r * (theta - theta_cmd))
        
        # 2. Periodic cogging torque
        tau_cogging = -self.T_cog * np.sin(self.N_cog * theta)
        
        # 3. Low-level friction losses (Viscous + Coulomb)
        tau_friction = -self.B_m * theta_dot - self.T_coulomb * np.tanh(100.0 * theta_dot)
        
        return tau_em + tau_cogging + tau_friction

class BoomArray:
    """3 actuated 1-DOF booms mounted on the satellite chassis."""
    def __init__(self, config):
        self.axes = np.array([
            axis / np.linalg.norm(axis) for axis in config['boom_axes']
        ])  # (3, 3) normalized hinge unit vectors
        
        self.inertias = np.array(config['boom_inertias'])  # (3,) moments of inertia about hinges
        self.m_booms = np.array(config.get('m_booms', [0.1, 0.1, 0.1]))  # kg
        self.l_booms = np.array(config.get('l_booms', [0.5, 0.5, 0.5]))  # m
        self.r_hinges = np.array(config.get('r_hinges', [
            [0.05, 0.0, 0.0], 
            [0.0, 0.05, 0.0], 
            [0.0, 0.0, 0.05]
        ]))  # (3, 3) hinge attachment vectors in base body frame

        motor_cfg = config.get('motor_config', {})
        self.motors = [MicroStepperMotor(motor_cfg) for _ in range(3)]

    def _get_boom_rotation(self, i, theta_i):
        """Computes Rodrigues' rotation matrix for boom i by angle theta around its hinge axis."""
        a = self.axes[i]
        cos_t, sin_t = np.cos(theta_i), np.sin(theta_i)
        K = np.array([
            [0, -a[2], a[1]],
            [a[2], 0, -a[0]],
            [-a[1], a[0], 0]
        ])
        return np.eye(3) + sin_t * K + (1.0 - cos_t) * (K @ K)

    def compute_reaction_torque(self, theta, theta_dot, alpha_booms, w_base, use_motor = False):
        """
        Computes dynamic reaction torque and Coriolis torque acting on chassis from boom movement.
        """
        theta_ddot = np.zeros(3)
        tau_reaction = np.zeros(3)
        for i in range(3):
            axis_i = self.axes[i]
            J_boom = self.inertias[i]

            if use_motor:
                tau_motor = self.motors[i].compute_motor_torque(theta[i], theta_dot[i], alpha_booms[i]) # assume zero commanded angle for now
                theta_ddot[i] = float(tau_motor / J_boom)
                
                # Primary reaction torque from boom joint angular acceleration
                tau_reaction -= tau_motor * axis_i
            else:
                theta_ddot[i] = alpha_booms[i]
                # Primary reaction torque from boom joint angular acceleration
                tau_reaction -= J_boom * alpha_booms[i] * axis_i
            
            # Gyroscopic/Coriolis torque coupling boom joint rate and base angular velocity
            tau_reaction -= J_boom * np.cross(w_base, theta_dot[i] * axis_i)

        return theta_ddot,tau_reaction


class Magnetorquer:
    """3-axis magnetic torque rods for momentum desaturation."""
    def __init__(self, config):
        self.m_max = config.get('m_max', 0.2)  # Maximum magnetic dipole moment (A*m^2)

    def compute_torque(self, m_cmd, B_body):
        """
        Computes torque from magnetic dipole moment m in local magnetic field B: tau = m x B
        """
        m_clamped = np.clip(m_cmd, -self.m_max, self.m_max)
        return np.cross(m_clamped, B_body)
