import numpy as np


class MicroStepperMotor:
    """
    micro stepper motor model with EM stepping torque, cogging torque, and friction
    """

    def __init__(self, config):
        self.N_r = config.get('N_r', 50)               # Pole pairs (50 for 1.8 deg stepper)
        self.T_holding = config.get('T_holding', 0.15) # Peak holding torque [N*m]
        self.T_cog = config.get('T_cog', 0.008)        # Cogging torque peak amplitude [N*m]
        self.N_cog = config.get('N_cog', 200)          # Cogging cycles per revolution
        self.B_m = config.get('B_m', 1e-3)             # Viscous damping coefficient [N*m*s/rad]
        self.T_coulomb = config.get('T_coulomb', 0.002) # Coulomb dry friction torque [N*m]

    def compute_motor_torque(self, theta, theta_dot, theta_cmd):
        """
        Computes net torque generated by stepper motor at joint angle theta.
        """
        # 1. Electromagnetic stepping drive torque
        tau_em = -self.T_holding * np.sin(self.N_r * (theta - theta_cmd))
        
        # 2. Periodic cogging torque
        tau_cogging = -self.T_cog * np.sin(self.N_cog * theta)
        
        # 3. Low-level friction losses (Viscous + Coulomb)
        tau_friction = -self.B_m * theta_dot - self.T_coulomb * np.tanh(100.0 * theta_dot)
        
        return tau_em + tau_cogging + tau_friction

def default_boom_dirs(axes):
    dirs = []
    for a in np.asarray(axes, dtype=float):
        a = a / np.linalg.norm(a)
        ref = np.zeros(3)
        ref[np.argmin(np.abs(a))] = 1.0           # coordinate axis least aligned with the hinge
        d = ref - np.dot(ref, a) * a
        dirs.append(d / np.linalg.norm(d))
    return np.array(dirs)


class BoomArray:
    """3 actuated 1-DOF booms mounted on the satellite chassis."""
    def __init__(self, config):
        self.axes = np.array([
            axis / np.linalg.norm(axis) for axis in config['boom_axes']
        ])  # (3, 3) normalized hinge unit vectors
        
        self.m_rods = np.array(config.get('m_rods', [0.1, 0.1, 0.1]))  # kg
        self.m_tips = np.array(config.get('m_tips', [0.05, 0.05, 0.05]))  # kg
        self.l_rods = np.array(config.get('l_rods', [0.5, 0.5, 0.5]))  # m
        self.r_hinges = np.array(config.get('r_hinges', [
            [0.05, 0.0, 0.0], 
            [0.0, 0.05, 0.0], 
            [0.0, 0.0, 0.05]
        ]))  # (3, 3) hinge attachment vectors in base body frame

        if 'boom_dirs' in config:
            d = np.array(config['boom_dirs'], dtype=float)
            d = d - np.sum(d * self.axes, axis=1, keepdims=True) * self.axes
            self.boom_dirs = d / np.linalg.norm(d, axis=1, keepdims=True)
        else:
            self.boom_dirs = default_boom_dirs(self.axes)

        self.inertias = (1.0 / 3.0) * self.m_rods * (self.l_rods**2) + self.m_tips * (self.l_rods**2)

        motor_cfg = config.get('motor_config', {})
        self.motors = [MicroStepperMotor(motor_cfg) for _ in range(3)]

    def _get_boom_rotation(self, i, theta_i):
        """Computes Rodrigues' rotation matrix for boom i by angle theta around its hinge axis."""
        a = self.axes[i]
        cos_t, sin_t = np.cos(theta_i), np.sin(theta_i)
        K = np.array([
            [0, -a[2], a[1]],
            [a[2], 0, -a[0]],
            [-a[1], a[0], 0]
        ])
        return np.eye(3) + sin_t * K + (1.0 - cos_t) * (K @ K)

    def geometry(self, i, theta_i):
        """
        Boom i at hinge angle theta_i, in the base body frame.
        Returns (r_com, r_tip, J_rod_body): rod COM position, tip-mass position, and the rod's
        inertia about its own COM (thin rod of length l: m*l^2/12 * (I - d d^T), d = boom direction).
        """
        d = self._get_boom_rotation(i, theta_i) @ self.boom_dirs[i]
        l = self.l_rods[i]
        r_com = self.r_hinges[i] + 0.5 * l * d
        r_tip = self.r_hinges[i] + l * d
        J_rod_body = (1.0 / 12.0) * self.m_rods[i] * l**2 * (np.eye(3) - np.outer(d, d))
        return r_com, r_tip, J_rod_body

    def momentum_vector(self, i, theta_i):
        """
        g_i(theta_i) = d(H)/d(theta_dot_i): angular momentum about the chassis CoM (body frame)
        per unit hinge rate of boom i, with the chassis held fixed.

            g_i = J_rod_body a + sum_over_masses m * r x (a x (r - r_hinge))

        Reduces to J_boom * a when the hinge sits at the chassis CoM; otherwise it also has
        off-axis components from the hinge offset.
        """
        a, r_h = self.axes[i], self.r_hinges[i]
        r_com, r_tip, J_rod_body = self.geometry(i, theta_i)
        g = J_rod_body @ a
        for m, r in ((self.m_rods[i], r_com), (self.m_tips[i], r_tip)):
            g = g + m * np.cross(r, np.cross(a, r - r_h))
        return g

    def momentum_vector_rate(self, i, theta_i):
        """d(g_i)/d(theta_i), analytic."""
        a, r_h = self.axes[i], self.r_hinges[i]
        r_com, r_tip, J_rod_body = self.geometry(i, theta_i)
        g_rate = np.cross(a, J_rod_body @ a)
        for m, r in ((self.m_rods[i], r_com), (self.m_tips[i], r_tip)):
            v = np.cross(a, r - r_h)                 # dr/dtheta
            g_rate = g_rate + m * np.cross(r, np.cross(a, v))   # (v x v) term is zero
        return g_rate

    def compute_reaction_torque(self, theta, theta_dot, alpha_booms, w_base, use_motor = False):
        """
        Torque on the chassis from boom motion, from conservation of total angular momentum
        H = J(theta) w + sum_i g_i(theta_i) theta_dot_i :

            tau_reaction = -sum_i [ g_i * theta_ddot_i + g_i' * theta_dot_i^2 + theta_dot_i * (w x g_i) ]

        The first term is the direct reaction to boom acceleration, the second the centripetal
        change of g_i with boom angle, and the third the gyroscopic coupling with chassis spin.
        (The J_dot * w term lives in WiggleSat.state_derivative.)
        Returns (theta_ddot, tau_reaction).
        """
        theta_ddot = np.zeros(3)
        tau_reaction = np.zeros(3)
        for i in range(3):
            if use_motor:
                tau_motor = self.motors[i].compute_motor_torque(theta[i], theta_dot[i], alpha_booms[i])
                theta_ddot[i] = float(tau_motor / self.inertias[i])
            else:
                theta_ddot[i] = alpha_booms[i]

            g = self.momentum_vector(i, theta[i])
            g_rate = self.momentum_vector_rate(i, theta[i])
            tau_reaction -= (g * theta_ddot[i]
                             + g_rate * theta_dot[i] ** 2
                             + theta_dot[i] * np.cross(w_base, g))

        return theta_ddot, tau_reaction


class Magnetorquer:
    """3-axis magnetic torque rods for momentum desaturation."""
    def __init__(self, config):
        self.m_max = config.get('m_max', 0.2)  # Maximum magnetic dipole moment (A*m^2)

    def compute_torque(self, m_cmd, B_body):
        """
        Computes torque from magnetic dipole moment m in local magnetic field B: tau = m x B
        """
        m_clamped = np.clip(m_cmd, -self.m_max, self.m_max)
        return np.cross(m_clamped, B_body)